# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-09 20:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0002_barrio_colegio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscripcion',
            old_name='pin',
            new_name='codigo_inscripcion',
        ),
    ]
