# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-09 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0005_auto_20161109_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='tipo_id_inscripcion',
            field=models.IntegerField(choices=[(0, 'Seleccione'), (1, 'TI'), (2, 'CC'), (3, 'CE')], default=0),
        ),
    ]
