# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-09 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0006_inscripcion_tipo_id_inscripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripcion',
            name='nombre',
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='apellido_inscripcion',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='nombre_inscripcion',
            field=models.CharField(default='', max_length=120),
        ),
    ]
