# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-09 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0008_auto_20161109_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripcion',
            name='barrio',
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='barrio_inscripcion',
            field=models.IntegerField(choices=[(0, 'Seleccione'), (101, 'Terr\xf3n Colorado'), (102, 'Vista Hermosa'), (196, 'Sector Patio Bonito'), (199, 'Aguacatal'), (201, 'Santa Rita'), (202, 'Santa Teresita'), (203, 'Arboledas'), (204, 'Normand\xeda'), (205, 'Juanamb\xfa'), (206, 'Centenario'), (207, 'Granada'), (208, 'Versalles'), (209, 'San Vicente'), (210, 'Santa M\xf3nica '), (211, 'Prados del Norte'), (212, 'La Flora'), (213, 'La Campi\xf1a'), (214, 'La Paz'), (215, 'El Bosque'), (216, 'Menga'), (217, 'Ciudad Los \xc1lamos'), (218, 'Chipichape'), (219, 'Brisas de los \xc1lamos'), (293, 'Urbanizaci\xf3n La Merced'), (294, 'Vipasa'), (295, 'Urbanizaci\xf3n La Flora'), (296, 'Altos de Menga'), (297, 'Sector Altos Normand\xeda - Batacl\xe1n '), (298, '\xc1rea en desarrollo - Parque del Amor'), (301, 'El Nacional'), (302, 'El Pe\xf1\xf3n')], default=0),
        ),
    ]
