# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-09 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0009_auto_20161109_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='estrato_inscripcion',
            field=models.IntegerField(choices=[(0, 'Seleccione'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], default=0),
        ),
    ]
