# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-09 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0010_inscripcion_estrato_inscripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='comuna_inscripcion',
            field=models.IntegerField(choices=[(0, 'Seleccione'), (1, b'1'), (2, b'2'), (3, b'3'), (4, b'4'), (5, b'5'), (6, b'6'), (7, b'7'), (8, b'8'), (9, b'9'), (10, b'10'), (11, b'11'), (12, b'12'), (13, b'13'), (14, b'14'), (15, b'15'), (16, b'16'), (17, b'17'), (18, b'18'), (19, b'19'), (20, b'20'), (21, b'21'), (22, b'22')], default=0),
        ),
    ]
