# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-09 20:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0013_inscripcion_municipio_inscripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscripcion',
            old_name='celular',
            new_name='telefono_inscripcion',
        ),
    ]
