# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-09 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0014_auto_20161109_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripcion',
            name='email',
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='email_inscripcion',
            field=models.CharField(default='', max_length=120),
        ),
    ]
