# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-09 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0015_auto_20161109_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='n_acudiente_inscripcion',
            field=models.CharField(default='', max_length=120),
        ),
    ]
