# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-09 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0016_inscripcion_n_acudiente_inscripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='telefono_acudiente_inscripcion',
            field=models.CharField(default='', max_length=120),
        ),
    ]
