# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-09 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0017_inscripcion_telefono_acudiente_inscripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripcion',
            name='estadoCivil',
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='estado_civil_inscripcion',
            field=models.IntegerField(choices=[(0, 'Seleccione'), (1, 'Soltero'), (2, 'Casado'), (3, 'Viudo'), (3, 'Divorciado')], default=0),
        ),
    ]
