# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-09 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0018_auto_20161109_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripcion',
            name='numeroHijos',
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='n_hijos_inscripcion',
            field=models.IntegerField(choices=[(0, 'Seleccione'), (1, '0'), (2, '1'), (3, '2'), (4, 'Mas')], default=0),
        ),
    ]
