# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-09 20:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0019_auto_20161109_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripcion',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='estrato',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='municipio',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='nombreAcudiente',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='telefonoAcudiente',
        ),
    ]
