# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-09 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0022_auto_20161109_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='p_global_icfes_inscripcion',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='p_ing_icfes_inscripcion',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='p_lec_icfes_inscripcion',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='p_mat_icfes_inscripcion',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='p_nat_icfes_inscripcion',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='p_soc_icfes_inscripcion',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='registro_icfes_inscripcion',
            field=models.CharField(default='', max_length=120),
        ),
    ]
