# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-09 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0023_auto_20161109_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripcion',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='notas',
        ),
    ]
