# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-09 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0024_auto_20161109_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='a_bachiller_inscripcion',
            field=models.FileField(default='', upload_to='acta/'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='cedula_inscripcion',
            field=models.FileField(default='', upload_to='id/'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='cer_votacion_inscripcion',
            field=models.FileField(default='', upload_to='certificado/'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='p_academico_inscripcion',
            field=models.IntegerField(choices=[(0, 'Seleccione'), (3743, 'Ingenieria de Sistemas'), (3744, 'Ingenieria Electronica'), (3660, 'Medicina y Cirugia'), (3569, 'Fonoaudiologia')], default=0),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='sede_p_inscripcion',
            field=models.IntegerField(choices=[(0, 'Seleccione'), (1, 'Cali')], default=0),
        ),
    ]
