# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-11 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0025_auto_20161109_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='cer_votacion_inscripcion',
            field=models.FileField(blank=True, default='', null=True, upload_to='certificado/'),
        ),
    ]
