# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-14 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0026_auto_20161111_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='p_academico_inscripcion',
            field=models.IntegerField(choices=[(0, 'Seleccione'), (3743, 'Ingenieria de Sistemas'), (3660, 'Medicina y Cirugia'), (3569, 'Fonoaudiologia'), (3744, 'Ingenieria Electronica')], default=0),
        ),
    ]
