# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-17 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0027_auto_20161114_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='habilitado_inscripcion',
            field=models.BooleanField(default=True),
        ),
    ]
