# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-23 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0028_inscripcion_habilitado_inscripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='codigo_inscripcion',
            field=models.CharField(default='', max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='numero_id_inscripcion',
            field=models.CharField(default='', max_length=120, unique=True),
        ),
    ]
