# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-26 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0029_auto_20161123_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='mot_deshabilitacion',
            field=models.CharField(default='', max_length=200),
        ),
    ]
