# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-26 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0030_inscripcion_mot_deshabilitacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='mot_deshabilitacion',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
